source 'https://github.com/CocoaPods/Specs.git'

# Uncomment the next line to define a global platform for your project
platform :ios, '8.0'

target 'RealmJSONDemo' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  use_frameworks!

  # Pods for RealmJSONDemo
  pod 'AFNetworking'
  pod 'Realm+JSON', :path => '../'

  target 'RealmJSONDemoTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
